info:
  app:
    name: "Spring Boot 3 + Actuator"
    version: "1.0.0"
    description: "?????? ?????????? ? Actuator"
management:
  endpoint:
    health:
      probes:
        enabled: true  # ???????? ??? ?????: liveness ? readiness
      show-details: always  # ?????????? ?????? ? ????????
  info:
    env:
      enabled: true  # ???????? ?????????? ? ?????
  endpoints:
    web:
      exposure:
        include: "*" # ??????????? ?????????


