version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"  # Доступ к Prometheus через порт 9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Монтируем файл конфигурации
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  # Доступ к Grafana через порт 3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Пароль для администратора Grafana
    networks:
      - monitoring
    depends_on:
      - prometheus  # Grafana зависит от Prometheus

  spring-boot-app:
    image: your-spring-boot-app-image  # Укажите свой образ Spring Boot приложения с интеграцией Micrometer/Prometheus
    container_name: spring-boot-app
    ports:
      - "8080:8080"  # Пример, приложение доступно на порту 8080
    networks:
      - monitoring
    environment:
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,metrics,prometheus  # Открытие метрик
      - MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED=true  # Включение эндпоинта Prometheus

networks:
  monitoring:
    driver: bridge