server:
  port: 8082
spring:
  application:
    name: App actuator
#  boot:
#    admin:
#      client:
#        url: "http://localhost:8083"
#  datasource:
#    url: jdbc:postgresql://localhost:5532/postgres
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect


info:
  app:
    name: "Spring Boot 3 + Actuator"
    version: "1.0.0"
    description: "Spring boot actuator"
management:
  endpoint:
    health:
      probes:
        enabled: true #включить пробы
      show-details: always  #отображать детальную информацию и здоровье
  info:
    env: #каждое свойство можно вкл/выкл отдельно (build, env, git, java, os, process, ssl)
      enabled: true
    defaults:
      enabled: true #дефолтные значения
  endpoints:
    web:
      exposure:
        include: "*"



