server:
  port: 8083
spring:
  application:
    name: App trace

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
info:
  app:
    name: "Spring Boot 3 + trace"
    version: "1.0.0"
    description: "Spring boot trace"
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: app-trace
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'
  tracing:
    sampling:
      probability: 1.0  # Включает трассировку для всех запросов
#  zipkin:
#    tracing:
#      endpoint: http://host.docker.internal:9411/api/v2/spans
#      read-timeout: 2s
#      encoding: JSON




